# Generated by Django 4.0.4 on 2022-04-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_tag_task_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
